post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "4"
    end
  end
end

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iOSExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'SDAutoLayout', '~> 2.1.3'
end
